# Generated by Django 2.2 on 2019-04-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overview', '0002_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('unit', models.IntegerField()),
                ('desc', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('cost_per_tab', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_exercise_detail', to='overview.Pharmacy')),
            ],
        ),
    ]
