# Generated by Django 2.2 on 2019-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20190408_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='cost_per_tab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
