# Generated by Django 2.2 on 2019-04-25 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_auto_20190415_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 10, 1, 51, 403673)),
        ),
        migrations.AddField(
            model_name='drug',
            name='profit_per_tab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='drug',
            name='shelf_number',
            field=models.IntegerField(default=1),
        ),
    ]
