# Generated by Django 2.2 on 2019-04-27 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0007_auto_20190427_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 27, 5, 45, 58, 502783)),
        ),
    ]
