# Generated by Django 2.2 on 2019-04-29 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0012_auto_20190429_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 0, 37, 0, 467129)),
        ),
    ]
