# Generated by Django 2.2 on 2019-04-29 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0013_auto_20190429_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 4, 49, 20, 583580)),
        ),
    ]
