# Generated by Django 2.2 on 2019-04-29 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0018_auto_20190429_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 22, 31, 48, 686594)),
        ),
    ]
