# Generated by Django 2.2 on 2019-04-30 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0019_auto_20190429_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 8, 38, 5, 730204)),
        ),
    ]
