# Generated by Django 2.2 on 2019-04-30 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0023_auto_20190430_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2019, 5, 30)),
        ),
    ]
