# Generated by Django 2.2 on 2019-05-01 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0024_auto_20190430_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2019, 5, 31)),
        ),
    ]
