# Generated by Django 2.2 on 2019-04-22 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
