# Generated by Django 2.2 on 2019-04-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_stock_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='cost_per_tab',
            field=models.IntegerField(default=0),
        ),
    ]
