# Generated by Django 2.2 on 2019-04-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190422_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='cost_per_tab',
            field=models.IntegerField(),
        ),
    ]
