# Generated by Django 2.2 on 2019-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190422_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='cost_per_tab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
