# Generated by Django 2.2 on 2019-04-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190427_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.Stock'),
        ),
    ]
