# Generated by Django 2.2 on 2019-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='profit_per_tab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_profit',
            field=models.IntegerField(default=0),
        ),
    ]
