# Generated by Django 2.2 on 2019-04-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_userstockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorder', to='company.UserStock'),
        ),
    ]
