# Generated by Django 2.2 on 2019-04-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_auto_20190425_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isadmin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
