# Generated by Django 2.2 on 2019-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_customuser_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isadmin',
            field=models.CharField(blank=True, default='User', max_length=255),
        ),
    ]
